// auth & user
export const SET_USER = "SET_USER"
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED"
export const SET_LOADING_USER = "SET_LOADING_USER"
export const ADD_TOURNAMENT = "ADD_TOURNAMENT"
export const UPDATE_TOURNAMENT = "UPDATE_TOURNAMENT"

// ui
export const SET_LOADING_UI = "SET_LOADING_UI"
export const STOP_LOADING_UI = "STOP_LOADING_UI"
export const ADD_ERROR = "ADD_ERROR"
export const CLEAR_ERRORS = "CLEAR_ERRORS"

// data
export const SET_LOADING_DATA = "SET_LOADING_DATA"
export const SET_FEED = "SET_FEED"
export const SET_AREA_TOURNAMENTS = "SET_AREA_TOURNAMENTS"
export const SET_TOURNAMENT = "SET_TOURNAMENT"
export const SIGN_UP_TO_TOURNAMENT = "SIGN_UP_TO_TOURNAMENT"
export const SIGN_OFF_FROM_TOURNAMENT = "SIGN_OFF_FROM_TOURNAMENT"
export const SET_WINNER = "SET_WINNER"
