// auth & user
export const SET_USER = "SET_USER"
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED"
export const UPDATE_USER = "UPDATE_USER"
export const SET_LOADING_USER = "SET_LOADING_USER"

// ui
export const SET_LOADING_UI = "SET_LOADING_UI"
export const STOP_LOADING_UI = "STOP_LOADING_UI"
export const ADD_ERROR = "ADD_ERROR"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const SET_ACTION_STATUS = "SET_ACTION_STATUS"
export const CLEAR_ACTION = "CLEAR_ACTION"

// data
export const SET_LOADING_DATA = "SET_LOADING_DATA"
export const SET_FEED = "SET_FEED"
export const SET_AREA_TOURNAMENTS = "SET_AREA_TOURNAMENTS"
export const SET_TOURNAMENT = "SET_TOURNAMENT"
export const SIGN_UP_TO_TOURNAMENT = "SIGN_UP_TO_TOURNAMENT"
export const SIGN_OFF_FROM_TOURNAMENT = "SIGN_OFF_FROM_TOURNAMENT"
export const SET_WINNER = "SET_WINNER"
export const ADD_TOURNAMENT = "ADD_TOURNAMENT"
export const UPDATE_TOURNAMENT = "UPDATE_TOURNAMENT"

export const SET_USERS_FOUND = "SET_USERS_FOUND"
export const SET_USER_PROFILE = "SET_USER_PROFILE"

// actions status
export const STATUS_TOURNAMENT_ADDED = "STATUS_TOURNAMENT_ADDED"
export const STATUS_TOURNAMENT_UPDATED = "STATUS_TOURNAMENT_UPDATED"
export const STATUS_PROFILE_UPDATED = "STATUS_PROFILE_UPDATED"
export const STATUS_ACCOUNT_CREATED = "STATUS_ACCOUNT_CREATED"
export const STATUS_ACCOUNT_DELETED = "STATUS_ACCOUNT_DELETED"
