export const sentences = [
    "“The elevator to success is out of order. You'll have to use the stairs, one step at a time.” — Joe Girard",
    "“I am so clever that sometimes I don’t understand a single word of what I am saying.” — Oscar Wilde",
    "“Work until your bank account looks like a phone number.” — Unknown ",
    "“Life is like a sewer… what you get out of it depends on what you put into it.” — Tom Lehrer",
    "“I always wanted to be somebody, but now I realise I should have been more specific.” — Lily Tomlin",
    "“Just one small positive thought in the morning can change your whole day.” — Dalai Lama",
    "“Opportunities don't happen, you create them.” — Chris Grosser",
    "“Love your family, work super hard, live your passion.” — Gary Vaynerchuk",
    "“It is never too late to be what you might have been.” — George Eliot",
    "“Don't let someone else's opinion of you become your reality” — Les Brown",
    "“Can we pretend that airplanes in the night sky are like shootin' stars?” — Hayley N. Williams",
    "“Hey now, you're an all-star, get your game on, go play” — Steven Harwell",
    "“We know the game and we're gonna play it” — Rick Astley",
]
